all: worm_hole_surfer.lpr
	fpc -Fu"../../../zizutils/pascal_headers/" -Fl"../../../zizutils/" worm_hole_surfer.lpr -oworm_hole_surfer.so -Xs -XX -fPIC

debug: worm_hole_surfer.lpr
	fpc -Fu"../../../zizutils/pascal_headers/" -Fl"../../../zizutils/" worm_hole_surfer.lpr -oworm_hole_surfer.so -gw -fPIC
