all: Energizer.pp
	fpc -Fu"../../../zizutils/pascal_headers/" -Fl"../../../zizutils/" Energizer.pp -oEnergizer.so -Xs -XX -fPIC

debug: Energizer.pp
	fpc -Fu"../../../zizutils/pascal_headers/" -Fl"../../../zizutils/" Energizer.pp -oEnergizer.so -gw -fPIC
