# Project: simple_snake
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = simple_snake.o $(RES)
LINKOBJ  = simple_snake.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib" --no-export-all-symbols --add-stdcall-alias -lSDL -lSDL_image -lopengl32 -lglu32 -lSDL_ttf -lSDL_mixer ../../../zizutils/liblibzizopenparty.a  -mwindows 
INCS =  -I"C:/Dev-Cpp/include" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include" 
BIN  = simple_snake.dll
CXXFLAGS = $(CXXINCS) -DBUILDING_DLL=1   -mwindows
CFLAGS = $(INCS) -DBUILDING_DLL=1   -mwindows
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before simple_snake.dll all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

DLLWRAP=dllwrap.exe
DEFFILE=libsimple_snake.def
STATICLIB=libsimple_snake.a

$(BIN): $(LINKOBJ)
	$(DLLWRAP) --output-def $(DEFFILE) --implib $(STATICLIB) $(LINKOBJ) $(LIBS) -o $(BIN)

simple_snake.o: simple_snake.c
	$(CC) -c simple_snake.c -o simple_snake.o $(CFLAGS)
