all: king_pong.pp
	fpc -Fu"../../../zizutils/pascal_headers/" -Fl"../../../zizutils/" king_pong.pp -oking_pong.so -Xs -XX -fPIC

debug: king_pong.pp
	fpc -Fu"../../../zizutils/pascal_headers/" -Fl"../../../zizutils/" king_pong.pp -oking_pong.so -gw -fPIC
