all: ikosaeder_implosion.pp
	fpc -Fu"../../../zizutils/pascal_headers/" -Fl"../../../zizutils/" ikosaeder_implosion.pp -oikosaeder_implosion.so -Xs -XX -fPIC

debug: ikosaeder_implosion.pp
	fpc -Fu"../../../zizutils/pascal_headers/" -Fl"../../../zizutils/" ikosaeder_implosion.pp -oikosaeder_implosion.so -gw -fPIC
